### PR TITLE
Add a stub setup.py

### PR DESCRIPTION
**Pull request by astronouth7303**
Add a stub `setup.py`

This is required for editable installs. Which I use extensively, because I have a lot of venvs and sometimes I want my live development version.

### CODE REVIEW

**Comment by astronouth7303** [comment]
"Just run it from the local directory" doesn't cover:

* The CLI entry point
* Using the dev version in other contexts

**Comment by duckinator** [comment]
Despite https://github.com/duckinator/bork/commit/f5bae789aed8c73297ef730329b6918858db2fb2, I'm actually in favor of this and was considering it for the same reason. I mostly removed it to _force_ myself to use bork to release itself and get it as streamlined as possible, and... well... I find it easier to release it using bork than with a setup.py-based setup, now, so I think I succeeded lol

bors r+

**Comment by duckinator** [comment]
That said, I really hope they do find a way to do editable installs with PEP 517 projects. It'd be really nice.

**Comment by astronouth7303** [comment]
I'm also switching between poetry and setuptools a lot, so bork is nice.

**Pull request merged**
